
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ESHOP
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        incorrectUPLbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JButton();
        loginHeadLbl = new javax.swing.JLabel();
        incorrectUPLbl = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        showPassCb = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setBackground(new java.awt.Color(204, 204, 204));
        closeBtn.setForeground(new java.awt.Color(0, 118, 221));
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        loginHeadLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        loginHeadLbl.setForeground(new java.awt.Color(0, 118, 221));
        loginHeadLbl.setText("Login");
        getContentPane().add(loginHeadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, -1, -1));

        incorrectUPLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        incorrectUPLbl.setForeground(new java.awt.Color(255, 0, 0));
        incorrectUPLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        incorrectUPLbl.setText("Incorrect Username or Password");
        getContentPane().add(incorrectUPLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        usernameTxt.setBackground(new java.awt.Color(255, 255, 255));
        usernameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(0, 118, 221));
        usernameTxt.setText("Enter Username");
        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTxtFocusLost(evt);
            }
        });
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 304, -1));

        passwordTxt.setBackground(new java.awt.Color(255, 255, 255));
        passwordTxt.setForeground(new java.awt.Color(0, 118, 221));
        passwordTxt.setText("Enter Password");
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 304, -1));

        loginBtn.setBackground(new java.awt.Color(204, 204, 204));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 118, 221));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        showPassCb.setBackground(new java.awt.Color(255, 255, 255));
        showPassCb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showPassCb.setForeground(new java.awt.Color(0, 118, 221));
        showPassCb.setText("Show Password");
        showPassCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassCbActionPerformed(evt);
            }
        });
        getContentPane().add(showPassCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login background.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusGained
        // TODO add your handling code here:
        incorrectUPLbl.setVisible(false);
        if(usernameTxt.getText().equals ("Enter Username")){
            usernameTxt.setText("");
            usernameTxt.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_usernameTxtFocusGained

    private void usernameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusLost
        // TODO add your handling code here:
        incorrectUPLbl.setVisible(false);
        if (usernameTxt.getText().equals ("")){
            usernameTxt.setText("Enter Username");
            usernameTxt.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_usernameTxtFocusLost

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
        // TODO add your handling code here:
        incorrectUPLbl.setVisible(false);
        if(passwordTxt.getText().equals ("Enter Password")){
            passwordTxt.setText("");
            passwordTxt.setForeground(new Color(0,118,221));
        }
        
    }//GEN-LAST:event_passwordTxtFocusGained

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
        // TODO add your handling code here:
         incorrectUPLbl.setVisible(false);
        if (passwordTxt.getText().equals ("")){
            passwordTxt.setText("Enter Password");
            passwordTxt.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_passwordTxtFocusLost

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to exit?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        if (usernameTxt.getText().equals("iabdullahsadiq") && passwordTxt.getText().equals("81962")||usernameTxt.getText().equals("abdulwahabaslam") && passwordTxt.getText().equals("81988")){
            setVisible(false);
            new Home().setVisible(true);
        }
        else{
            incorrectUPLbl.setVisible(true);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void showPassCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassCbActionPerformed
        // TODO add your handling code here:
        if (showPassCb.isSelected()){
            passwordTxt.setEchoChar((char)0);
        }
        else {
            passwordTxt.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassCbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel incorrectUPLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginHeadLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JCheckBox showPassCb;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
